// General Actions
export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE'
export const RESET_SUCCESS_MESSAGE = 'RESET_SUCCESS_MESSAGE'

// Layout
export const LAYOUT_TOGGLE_NAVBAR = 'LAYOUT_TOGGLE_NAVBAR'